const Views = {
  Manager: Symbol.for("ViewManager"),
  View: Symbol.for("View"),
  Chat: Symbol.for("ChatView"),
  Character: Symbol.for("CharacterView"),
  Dice: Symbol.for("DiceView"),
  Gm: Symbol.for("GmView"),
  Scene: Symbol.for("SceneView"),
  Encyclopedia: Symbol.for("EncyclopediaView"),
  Ruler: Symbol.for("RulerView"),
  Zoom: Symbol.for("ZoomView"),
  TurnOrder: Symbol.for("TurnOrder"),
  TaskBar: Symbol.for("TaskBarView"),
  Ui: Symbol.for("Ui"),
  QuickBar: Symbol.for("QuickBar"),
  Craft: Symbol.for("CraftView"),
  Token: Symbol.for("TokenView"),
  Drawings: Symbol.for("DrawingsView"),
  Music: Symbol.for("MusicView"),
  Konsole: Symbol.for("KonsoleView"),
  Sound: Symbol.for("SoundView"),
  Book: Symbol.for("BookView"),
  Media: Symbol.for("MediaView"),
  Pdf: Symbol.for("PdfView"),
  DynamicLighting: Symbol.for("DynamicLightingView"),
  DiceRoller: Symbol.for("DiceRollerView"),
  SceneBrowser: Symbol.for("SceneBrowserView"),
};

export { Views };
