export interface Icon {
  path: string;
  tags?: string[];
}

export interface IconPack {
  id?: number | string;
  name: string;
  icons?: Icon[];
  shared_by?: string;
  pass?: string;
  user_id?: number;
}

export const DefaultIconPacks: IconPack[] = [
  {
    id: "default",
    name: "Default",
    icons: [
      { path: "icons/3hmeebdyo3w50rrt.jpg" },
      { path: "icons/mmywih8brfj5j4u7.jpg" },
      { path: "icons/oytnqmv110mcobv0.jpg" },
      { path: "icons/utlbgcsia2a37z73.jpg" },
      { path: "icons/l7jzunp4nzg5cd8w.jpg" },
      { path: "icons/riuzqtcl48cgfuvr.jpg" },
      { path: "icons/guvw314ljr76m4l0.jpg" },
      { path: "icons/riuz4o4a867wj25s.jpg" },
      { path: "icons/4ofor0nyu71zi2xg.jpg" },
      { path: "icons/p7hg0m814sv8argk.jpg" },
      { path: "icons/4aapqkw6cipa6518.jpg" },
      { path: "icons/pn86o8a0a1sy5umr.jpg" },
      { path: "icons/8qda5f2ewgjsr268.jpg" },
      { path: "icons/5oeuuqmwobx3xz3v.jpg" },
      { path: "icons/hbyltmb32zc18miw.jpg" },
      { path: "icons/otljgxnoqowqhbjv.jpg" },
      { path: "icons/pb8l166a3xgkldf0.jpg" },
      { path: "icons/oi2qpwdiin3ivqxi.jpg" },
      { path: "icons/on5aoxm0v2hyitfx.jpg" },
      { path: "icons/bspqrwdn5q8qqkyf.jpg" },
      { path: "icons/ovqbb2tdolzjgi67.jpg" },
      { path: "icons/wvtxa4ou07ws3l7k.jpg" },
      { path: "icons/0obtqgwyqupe1uc8.jpg" },
      { path: "icons/uy51g011f52f0tcs.jpg" },
      { path: "icons/e5gjnqzp5sh7hik7.jpg" },
      { path: "icons/5dpcl2tzrfdvdzv4.jpg" },
      { path: "icons/dd0bkk2itnfyo8wx.jpg" },
      { path: "icons/a74btio5j1immj1n.jpg" },
      { path: "icons/v7dp6ohp7d50glrg.jpg" },
      { path: "icons/heqx8wns0ganyvzv.jpg" },
    ],
  },
  {
    id: "status",
    name: "Token Status",
    icons: [
      { path: "icons/status/debuff-backstab.jpg" },
      { path: "icons/status/debuff-broken-shield.jpg" },
      { path: "icons/status/debuff-cancel.jpg" },
      { path: "icons/status/debuff-cross-mark.jpg" },
      { path: "icons/status/debuff-diamonds-smile.jpg" },
      { path: "icons/status/debuff-drowning.jpg" },
      { path: "icons/status/debuff-enrage.jpg" },
      { path: "icons/status/debuff-hazard-sign.jpg" },
      { path: "icons/status/debuff-hearing-disabled.jpg" },
      { path: "icons/status/debuff-imprisoned.jpg" },
      { path: "icons/status/debuff-knockout.jpg" },
      { path: "icons/status/debuff-open-wound.jpg" },
      { path: "icons/status/debuff-oppression.jpg" },
      { path: "icons/status/debuff-poison-bottle.jpg" },
      { path: "icons/status/debuff-stitched-wound.jpg" },
      { path: "icons/status/debuff-vomiting.jpg" },
      { path: "icons/status/buff-check-mark.jpg" },
      { path: "icons/status/buff-heart-plus.jpg" },
      { path: "icons/status/buff-hearts.jpg" },
      { path: "icons/status/buff-meditation.jpg" },
      { path: "icons/status/buff-muscle-up.jpg" },
      { path: "icons/status/buff-shaking-hands.jpg" },
      { path: "icons/status/buff-strong.jpg" },
      { path: "icons/status/death-death-skull.jpg" },
      { path: "icons/status/death-despair.jpg" },
      { path: "icons/status/death-hasty-grave.jpg" },
      { path: "icons/status/death-raise-zombie.jpg" },
      { path: "icons/status/death-shambling-zombie.jpg" },
      { path: "icons/status/death-skeletal-hand.jpg" },
      { path: "icons/status/death-tombstone.jpg" },
      { path: "icons/status/energy-aura.jpg" },
      { path: "icons/status/energy-battery-25.jpg" },
      { path: "icons/status/energy-battery-50.jpg" },
      { path: "icons/status/energy-battery-75.jpg" },
      { path: "icons/status/energy-battery-100.jpg" },
      { path: "icons/status/energy-deadly-strike.jpg" },
      { path: "icons/status/energy-eskimo.jpg" },
      { path: "icons/status/energy-explosive-materials.jpg" },
      { path: "icons/status/energy-fireflake.jpg" },
      { path: "icons/status/energy-fire-silhouette.jpg" },
      { path: "icons/status/energy-flamer.jpg" },
      { path: "icons/status/energy-gooey-molecule.jpg" },
      { path: "icons/status/energy-gooey-sword.jpg" },
      { path: "icons/status/energy-lightning-branches.jpg" },
      { path: "icons/status/energy-teleport.jpg" },
      { path: "icons/status/energy-web-spit.jpg" },
      { path: "icons/status/energy-yin-yang.jpg" },
      { path: "icons/status/mental-coma.jpg" },
      { path: "icons/status/mental-mute.jpg" },
      { path: "icons/status/mental-psychic-waves.jpg" },
      { path: "icons/status/mental-screaming.jpg" },
      { path: "icons/status/mental-semi-closed-eye.jpg" },
      { path: "icons/status/mental-sight-disabled.jpg" },
      { path: "icons/status/mental-silenced.jpg" },
      { path: "icons/status/mental-sleepy.jpg" },
      { path: "icons/status/mental-smitten.jpg" },
      { path: "icons/status/mental-sonic-shout.jpg" },
      { path: "icons/status/mental-surprised.jpg" },
      { path: "icons/status/mental-suspicious.jpg" },
      { path: "icons/status/mental-terror.jpg" },
      { path: "icons/status/avatar-baby-face.jpg" },
      { path: "icons/status/avatar-female-vampire.jpg" },
      { path: "icons/status/avatar-fox-head.jpg" },
      { path: "icons/status/avatar-gaze.jpg" },
      { path: "icons/status/avatar-ghost.jpg" },
      { path: "icons/status/avatar-goblin-head.jpg" },
      { path: "icons/status/avatar-king.jpg" },
      { path: "icons/status/avatar-medusa-head.jpg" },
      { path: "icons/status/avatar-mummy-head.jpg" },
      { path: "icons/status/avatar-ninja-head.jpg" },
      { path: "icons/status/avatar-one-eyed.jpg" },
      { path: "icons/status/avatar-robot-antennas.jpg" },
      { path: "icons/status/avatar-vampire-dracula.jpg" },
      { path: "icons/status/avatar-werewolf.jpg" },
      { path: "icons/status/avatar-wolf-head.jpg" },
      { path: "icons/status/avatar-wolf-howl.jpg" },
      { path: "icons/status/other-all-seeing-eye.jpg" },
      { path: "icons/status/other-angel-wings.jpg" },
      { path: "icons/status/other-attached-shield.jpg" },
      { path: "icons/status/other-boot-kick.jpg" },
      { path: "icons/status/other-drop-weapon.jpg" },
      { path: "icons/status/other-holy-symbol.jpg" },
      { path: "icons/status/other-mountain-climbing.jpg" },
      { path: "icons/status/other-musical-notes.jpg" },
      { path: "icons/status/other-night-sleep.jpg" },
      { path: "icons/status/other-spill.jpg" },
      { path: "icons/status/other-switch-weapon.jpg" },
    ],
  },
];
